### ISSUE TITLE
Missplaced on highway

### ISSUE THREAD

**Issue by xtreme00zzz** [Zerofour04/zero_checkpointmap#1]
The 3 signs that block the road southbound appear before the casino exit instead of pillbox hospital.

**Comment by Zerofour04** [comment]
Hey, thanks for that issue. I will fix that.

**Comment by Zerofour04** [comment]
### Issue #1
👋 Hey @xtreme00zzz,
I fixed your problem in this version: https://github.com/Zerofour04/Checkpoint-Route13/releases/tag/1.0.1
- removed the signs

Thanks for your support.
Sincerely 
_Ben_
